### ISSUE TITLE
Backend - npm start failed

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [Sujan-Kandeepan/Eruku-Mesi#46]
In GitLab by @lix229 on Mar 7, 2021, 17:21

# Summary
`npm start` will fail after `npm install` in `/backend`.

# Env
- macOS version: 11.2.2
- Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
``` bash
❯ npm version
{
  backend: '1.0.0',
  npm: '7.0.15',
  node: '15.4.0',
  v8: '8.6.395.17-node.22',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '88',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}

❯ node --version
v15.4.0

❯ expo --version
4.2.1
```

# Logs and Issue recreation
## Logs
```bash
❯ npm install

up to date, audited 601 packages in 1s

found 0 vulnerabilities

❯ npm start

> backend@1.0.0 start
> node server.js

Server is running on port: 4000
/Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/node_modules/mongoose/lib/connection.js:680
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/node_modules/mongoose/lib/connection.js:680:11)
    at /Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/node_modules/mongoose/lib/index.js:345:10
    at /Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/node_modules/mongoose/lib/index.js:1135:10)
    at Mongoose.connect (/Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/node_modules/mongoose/lib/index.js:344:20)
    at Object.<anonymous> (/Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/setup.js:14:10)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend/server.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR! code 1
npm ERR! path /Users/shawn/OneDrive/Documents/Forth_Year/4ZP6/externalTesting/eruku-mesi/backend
npm ERR! command failed
npm ERR! command sh -c node server.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shawn/.npm/_logs/2021-03-07T22_20_24_774Z-debug.log

```

## Issue recreation

1. `cd $PATH_TO_PROJECT/backend`
2. npm install
3. npm start // Failed with log message

**Comment by Sujan-Kandeepan** [comment]
In GitLab by @kandeeps on Mar 19, 2021, 11:53

assigned to @tut and @choij12

**Comment by Sujan-Kandeepan** [comment]
In GitLab by @tut on Mar 23, 2021, 18:23

Hey @lix229 , you need to ensure that you create a .env file and put the right information inside of the .env file. Once you do that, this would start working.
